# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: julia:1.1
    steps:
      - run:
          name: Install MolecBio
          command: julia -e  'using Pkg; pkg"add https://github.com/pkmklong/MolecBio.git";' pwd; ls
workflows:
  integration:
    jobs:
      - build
