# .circleci/config.yml
version: 2.1
defaults: &defaults
  docker:
    - image: julia:1.1
  working_directory: ~/project
  environment:
    BASH_ENV: "~/.bashrc"
    
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install MolecBio
          command: |
              julia -e  'using Pkg; pkg"add https://github.com/pkmklong/MolecBio";'
      - run:
          name: check path
          command: |  
              julia -e  'println(JULIA_LOAD_PATH); println(Base.load_path());'
      - run:
          name: Install git
          command: |
              apt-get update && \
              apt-get upgrade -y && \
              apt-get install -y git
      - run:
          name: clone MolecBio
          command: |                         
              git clone https://github.com/pkmklong/MolecBio.git
      - run:
          name: run demo
          command: |  
              julia MolecBio/src/runner.jl -f "data/demo_data.csv" -c "control" -t "egf1r" -n "rpl19"             
              
#     - save_cache:
#         key: "install_deps_3"
#         paths: 
#             - ~/.julia/*
#             - ~/.julia/registries/General
#             - /root/.bashrc
#             - ~/.julia/environments/v1.5/Project.toml
#             - ~/.julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5
#               
# demo:          
#     <<: *defaults
#     steps:
#       - checkout  # checkout source code to working directory
#       - restore_cache:
#            keys:
#              - "install_deps_3"
#       - run:
#           command: julia src/runner.jl -f "data/demo_data.csv" -c "control" -t "egf1r" -n "rpl19" 
  
workflows:
  integration:
    jobs:
      - build   
#   - demo:
#       requires:
#           - build
