# .circleci/config.yml
version: 2.1
defaults: &defaults
  docker:
    - image: julia:1.1
  working_directory: ~/project
    
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Install MolecBio
          command: |
              julia -e  'using Pkg; pkg"add https://github.com/pkmklong/MolecBio.git";' 
        - save_cache:
             key: "setup_deps"
             paths: 
                - ~/.julia/
                
  demo:          
      <<: *defaults
      steps:
        - checkout  # checkout source code to working directory
        - restore_cache:
             keys:
               - "setup_deps"
        - run:
            command: |
              pwd
              ls
  
workflows:
  integration:
    jobs:
      - build   
      - demo:
          requires:
              - build
